### ISSUE TITLE
'deepl' has no attribute 'Translator' 

### ISSUE THREAD

**Issue by DeveloperDW** [DeepLcom/deepl-python#13]
I receive an Error with the last Version (deepl 1.3.1) running the example on python 3.9 - 64 bit Windows 10

> translator = deepl.Translator("mykey")
> AttributeError: partially initialized module 'deepl' has no attribute 'Translator' (most likely due to a circular import)
> 

My SampleCode:

> 
> import os
> import deepl
> 
> translator = deepl.Translator("mykey")
> result = translator.translate_text("Hello, world!", target_lang="FR")
> print(result)
> 

Maybe a simple error, but i can't figure it out yet what i'am doing wrong. I hope somebody knows what to do.  Thanks for your help.

**Comment by daniel-jones-deepl** [comment]
Hi @DeveloperDW, thanks for the report. Your error might be caused by a naming clash:
- this file is named **deepl.py**
- another file in the same directory is named **deepl.py**
- the current directory or a subdirectory is named **deepl**

If any of these is true, try renaming them to see if it fixes the problem.

**Comment by DeveloperDW** [comment]
Yes, that was the issue , my fault... thanks for helping me out with this.

**Comment by daniel-jones-deepl** [comment]
Great, I'm glad it was a simple fix.

**Comment by vindexinsanctirex** [comment]
I have nothing called deepl in my project, yet I get this error no matter what I do, any ideas?
