### ISSUE TITLE
DeepLException

### ISSUE THREAD

**Issue by SamueLacombe** [DeepLcom/deepl-python#42]
Hello,

There is an example of DeepLException : 
`except deepl.DeepLException as error:
    # Errors during upload raise a DeepLException
    print(error)`

but 
1) I'm not sure how to check the error "code" returned (501, 404, etc)
2) I noticed in the source code that there is supposed to be an argument "should_retry". Should I expect this argument to be always present in my error and just have to do : 
`if error.should_retry:
       call again`
3) Having an example how to simulate an error returned by DeepL would be practical to debug.

Best regards,
Samuel

**Comment by daniel-jones-deepl** [comment]
Hi @SamueLacombe, thanks for the questions.

1. The HTTP status code is not included in the exception, because we didn't expect it to be needed. The HTTP status code is already checked by the library to choose the type of exception and message. Do you need it for your application?
2. The `should_retry` parameter is used internally when deciding whether to retry requests. The library retries failed requests, by default up to 5 times.
3. A few ways you could trigger errors: use an incorrect auth-key, use an invalid target or source language code, or try to translate an unsupported document type (e.g. image files).

Thanks for creating this issue; these things could be made more clear in the documentation.

**Comment by SamueLacombe** [comment]
Hello,

I had to implement a "Exponential Backoff" with google automl api. I was trying to implement it with deepl aswell, if ever it fail for specific reason on the server side, but without the error code, I could retry on useless errors.

I believe it's possible to get bad gateway randomly like any other API?

Best regards,
Samuel

**Comment by arski** [comment]
+1 to the above, just implementing some exception handling and I think it's very different based on the type of error. e.g. for 502 Service Unavailable (also 429, maybe 456..), I would just backoff and retry later.

For 404 Not Found or 400 Bad Request, I would raise it to my Sentry because likely I'm doing something wrong and retrying will just spam your servers.

**Comment by daniel-jones-deepl** [comment]
Hi Samuel, this library already retries failed requests with exponential backoff, so you might not need to implement it yourself. The function which decides whether to retry a request is [`http_client._should_retry()`](https://github.com/DeepLcom/deepl-python/blob/v1.9.0/deepl/http_client.py#L193). We retry 429 and >=500 (excluding 503), so a 502 error would be retried.

I will look into exposing the HTTP error code in exceptions, and possibly the `shouldRetry` flag as well.

**Comment by daniel-jones-deepl** [comment]
Hi again, sorry for the long delay. [v1.12.0](https://github.com/DeepLcom/deepl-python/releases/tag/v1.12.0) adds `should_retry` and (Optional) `http_status_code` to DeepLException. Please let me know if there are any problems.

**Comment by arski** [comment]
thank you!
